### ISSUE TITLE
Can't run more than 10 commands in a connection because the connection runs out of channels

### ISSUE THREAD

**Issue by reivilibre** [julienc91/pystassh#4]
Hi,

I noticed this problem with pystassh and have written this example code to reproduce it:

```python
from pystassh import Session

if __name__ == '__main__':
    sess = Session(hostname="lithium", username="scone")
    sess.connect()

    for _ in range(11):
        print(sess.execute("echo Hi!").stdout)
```

Running this prints 'Hi!' 10 times and then crashes with the error:
```
Traceback (most recent call last):
  File "/home/rei/work/demo.py", line 8, in <module>
    print(sess.execute("echo Hi!").stdout)
  File "/home/rei/work/.venv/lib/python3.9/site-packages/pystassh/session.py", line 190, in execute
    return self._channel.execute(command)
  File "/home/rei/work/.venv/lib/python3.9/site-packages/pystassh/channel.py", line 186, in execute
    with self:
  File "/home/rei/work/.venv/lib/python3.9/site-packages/pystassh/channel.py", line 57, in __enter__
    self.open()
  File "/home/rei/work/.venv/lib/python3.9/site-packages/pystassh/channel.py", line 41, in open
    raise exceptions.ChannelException(
pystassh.exceptions.ChannelException: Channel cannot be opened: b'Channel opening failure: channel 53 error (2) open failed'
```

I think this is because the library doesn't close channels properly.
I noticed that the library doesn't free channels when they're 'closed' as far as libssh is concerned...

I think I have a small patch that fixes this.

**Comment by julienc91** [comment]
Fix released in v1.2.1, thanks for your PR!
